### ISSUE TITLE
App fails to start after update

### ISSUE THREAD

**Issue by rsimplicio** [hotio/docker-nzbhydra2#1]
I updated the container via ansible tag from Cloudbox, and after the update, the container failed to go into a healthy state. When inspecting the docker logs, there were a ton of entries that read: 

```
[cont-init.d] 00-start-container: exited 0.
[cont-init.d] 01-install-app: executing...
[cont-init.d] 01-install-app: exited 0.
[cont-init.d] 03-mount-filesystems: executing...
[cont-init.d] 03-mount-filesystems: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
python: can't open file '/app/nzbhydra2wrapper.py': [Errno 2] No such file or directory
python: can't open file '/app/nzbhydra2wrapper.py': [Errno 2] No such file or directory
python: can't open file '/app/nzbhydra2wrapper.py': [Errno 2] No such file or directory
```

I tried refreshing from the ansible tag, removing the image and then redo-ing via the ansible tag, pulling the image manually, etc. but every time, that file is still missing. I did find the curl commands in the Docker file from commit https://github.com/hotio/docker-nzbhydra2/commit/fe529bdd8c769f7bda5fad511e38617c1349ba72 , and the container returns back to normal after running this manually inside the container, and changing the permissions.

**Comment by hotio** [comment]
is already fixed, do a new docker pull
