### ISSUE TITLE
Failed to connect to localhost port 5076: Connection refused

### ISSUE THREAD

**Issue by slayer991** [hotio/docker-nzbhydra2#3]
OS: CentOS 7   
Docker version 1.13.1, build b2f74b2/1.13.1  

Docker create:  
docker create \  
  --name=hydra2 \  
  -e PUID=0 \  
  -e PGID=0 \  
  -e TZ=America/New_York \  
  -p 5077:5077 \  
  -v /optconfig/nzbhydra2:/config \  
  -v /media/downloads:/downloads \  
  --restart unless-stopped \  
  docker.io/hotio/nzbhydra2:latest  
  
I'm getting the following health error:
curl: (7) Failed to connect to localhost port 5076: Connection refused

I have nothing else running on that port...checked docker and netstat to ensure I wasn't using 5076 and confirmed it was not in use.  

As a test, I deleted my configs and set root user/group.  Redownloaded the image and recreated.  Still the same issue.  Tried changing the ports.  Same issue.  

I fell back to the old image (update before the latest), no issues.

**Comment by hotio** [comment]
```
docker create \
--name=hydra2 \
-e PUID=0 \
-e PGID=0 \
-e TZ=America/New_York \
-p 5077:5077 \              <-------------5077
-v /optconfig/nzbhydra2:/config \          <-------------/optconfig/
-v /media/downloads:/downloads \
--restart unless-stopped \
docker.io/hotio/nzbhydra2:latest
```

Are these (see above) just typos or actual misconfiguration? Does the image actually work? Do you actually run hydra on port 5077? If you actually start hydra on 5077 inside the container, then that would explain the curl failing on 5076.

**Comment by slayer991** [comment]
Sorry, that was my config when I was testing on a different port.  It was working on 5076 prior to WatchTower upgrading the image.  

/optconfig is my NFS share where I store all my container configs.  Again, this was working perfectly fine prior to the upgrade.

I built a completely new CentOS 7 box last night...just to test and I received the same error.

I have a workaround in place (explicitly configuring my nzb index of choice in sonarr, radarr, etc) and I'm happy to help troubleshoot this...I just wanted to give you heads up.

**Comment by hotio** [comment]
I think, I'm supposed to help troubleshoot you, because for me everything is working fine...

**Comment by slayer991** [comment]
If everything is working well for you on a similar setup, I'll just close this issue.  I'm able to replicate on my new machine but it's ok...thanks for the response.

**Comment by hotio** [comment]
If you can write down every step you take from let's say a clean install in a vm, I might be able to reproduce it....but I have not enough info as it is right now, only thing that pops out is you running hydra on port 5077 which make the healthcheck fail indeed. It still isn't clear either if the entire app fails or just the healthcheck.

**Comment by hotio** [comment]
lets do this....

```
docker run --rm --name nzbhydra2TEST -p 5076:5076 -e TZ=Etc/UTC hotio/nzbhydra2
```

```
docker ps
```

show me the output

**Comment by s0mm3rb** [comment]
same issue
fixed it with --net=host instead of -p

I've migrated to docker and imported the previous backup
it worked until import

same with the other hydra2 images from linuxserver and theotherp
they work until you import a backup

hydra says it started in xx seconds but it refuses every connection
