### ISSUE TITLE
 Add support for prereleases

### ISSUE THREAD

**Issue by theotherp** [hotio/docker-nzbhydra2#4]
I'll add support for prereleases in the next version. These can be determined by the property `prerelease` of the GitHub release (e.g. https://api.github.com/repos/theotherp/nzbhydra2/releases/latest).

Would it be possible for the regular container to not update to these and add a new container or tag for the latest prerelease? 

To be honest I'm not aware of the build process and even how the containers are installed, so I'm not sure if this would even be possible.

Thanks!

**Comment by hotio** [comment]
sure no problem

**Comment by hotio** [comment]
Should be good to go, thanks for letting me know.
https://github.com/hotio/docker-nzbhydra2/commits/unstable

**Comment by theotherp** [comment]
That was fast, thanks!
