### ISSUE TITLE
Add container info to file

### ISSUE THREAD

**Issue by theotherp** [hotio/docker-nzbhydra2#7]
linuxserver.io just made a change that adds a file with some container info: https://github.com/linuxserver/docker-nzbhydra2/commit/1d213f19e8ec76403feb0f4d1fc2470cb1fde578 

I can read that file and show it in the GUI and add it to the debug infos.

Could you do the same? Ideally the file format would be the same, you can choose the path.

It would look like this:
```
ReleaseType=Pre-Release
PackageVersion=2.3.0-hotio1
PackageAuthor=hotio
```

`ReleaseType` is either `Pre-Release` or `Release`, `PackageVersion` is the NZBHydra2 tag plus whatever you put there to identify your container version, although that info is not necessary.

**Comment by hotio** [comment]
will do, thx

**Comment by hotio** [comment]
done

https://discord.gg/3SnkuKp

**Comment by hotio** [comment]
It seems you are loading it from a static location `File lsioPackageFile = new File("/app/nzbhydra2/package_info");`
Can this be made relative, something like `File lsioPackageFile = new File("../package_info");`?

**Comment by theotherp** [comment]
My plan was to just cycle all the known file locations, e.g. look in the current working folder, then the one above, etc. That commit was just to test it first. I wanted to wait with the release until all maintainers had included it.

**Comment by hotio** [comment]
ah ok
